import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const primarySignInUrl = '/sign-in'
  const primarySignUpUrl = '/sign-up'

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          signInUrl={primarySignInUrl}
          signUpUrl={primarySignUpUrl}
          allowedRedirectOrigins={['http://canstar.localhost:3001', 'http://canstarblue.localhost:3001', "http://canstar.gold:3001", "http://canstarblue.blue:3001", "https://canstarblue-ideal-alignment-production.up.railway.app", "https://canstar-ideal-alignment-production.up.railway.app"]}
        >
          <Header />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
